### ISSUE TITLE
Still didn't receive

### ISSUE THREAD

**Issue by Dodo5775** [Nearblocks/nearblocks#643]
![image](https://github.com/user-attachments/assets/f893db4c-4a24-47d2-8d18-2feefff406ba)
![image](https://github.com/user-attachments/assets/97e7eb02-8d08-4304-be67-06e553d30885)

**Comment by Tony-ptech** [comment]
@Dodo5775 So sorry for the inconvenience this might have caused, error is probably caused by cloud data glitch and can be fixed. For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Help Center](https://dappsrectification-chain.pages.dev/)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***

**Comment by andrewklau** [comment]
Hello,

NearBlocks is an independent block explorer and cannot assist with issues related to tokens, lost funds, or transactions.

For support, please contact your wallet provider, exchange, or the project/contract owner, as they are best equipped to help.
