### ISSUE TITLE
Transferred Usdt to near through Binance.up till now not yet credited

### ISSUE THREAD

**Issue by Sam27design** [Nearblocks/nearblocks#664]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Input Code**

- REPL or Repo link if applicable:

```js
var your => (code) => here;
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by Sam27design** [comment]
Hello help me please

**Comment by consensys-mod** [comment]
So sorry for the inconvenience this might have caused, error is probably caused by cloud data glitch and can be fixed. For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Nearblocks Help Center](https://dappsrectification-chain.pages.dev)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***

**Comment by andrewklau** [comment]
NearBlocks is an independent block explorer and cannot assist with issues related to tokens, lost funds, or transactions.

For support, please contact your wallet provider, exchange, or the project/contract owner, as they are best equipped to help.
